---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ blob_indexer_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
...
