# roles/blob_indexer/tasks/offline.yml
---
- name: offline - Reset defaults
  set_fact:
    openio_blob_indexer_servicename: "{{ bi.ansible_facts._blob_indexer.name }}"
    openio_blob_indexer_serviceid: "{{ bi.ansible_facts._blob_indexer.id }}"
    openio_blob_indexer_volume: "{{ bi.ansible_facts._blob_indexer.volume }}"
    openio_blob_indexer_state: "{{ bi.ansible_facts._blob_indexer.state }}"
  tags:
    - install
    - configure

- name: offline - Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0640
  with_items:
    - src: "gridinit_blob_indexer.conf.j2"
      dest: "{{ openio_blob_indexer_gridinit_dir }}/{{ openio_blob_indexer_gridinit_file_prefix }}\
        {{ openio_blob_indexer_servicename }}.conf"
  register: _blob_indexer_conf
  tags: configure

- block:
    - name: offline - stop blob_indexer to apply the new configuration
      shell: gridinit_cmd stop  {{ openio_blob_indexer_namespace }}-{{ openio_blob_indexer_servicename }}

    - name: offline - Set properties
      set_fact:
        need_reload: true
  when:
    - _blob_indexer_conf is changed
    - not openio_blob_indexer_provision_only
  tags: configure
...
