# roles/blob_indexer/tasks/present.yml
---

- name: present - Reset defaults
  set_fact:
    openio_blob_indexer_servicename: "{{ bi.ansible_facts._blob_indexer.name }}"
    openio_blob_indexer_serviceid: "{{ bi.ansible_facts._blob_indexer.id }}"
    openio_blob_indexer_volume: "{{ bi.ansible_facts._blob_indexer.volume }}"
    openio_blob_indexer_state: "{{ bi.ansible_facts._blob_indexer.state }}"

- name: present - Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "{{ openio_blob_indexer_volume }}"
    - path: "{{ openio_blob_indexer_sysconfig_dir }}/{{ openio_blob_indexer_servicename }}"
    - path: "/var/log/oio/sds/{{ openio_blob_indexer_namespace }}/{{ openio_blob_indexer_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"

- name: present - Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "blob_indexer.conf.j2"
      dest: "{{ openio_blob_indexer_sysconfig_dir }}/\
        {{ openio_blob_indexer_servicename }}/{{ openio_blob_indexer_servicename }}.conf"
    - src: "gridinit_blob_indexer.conf.j2"
      dest: "{{ openio_blob_indexer_gridinit_dir }}/{{ openio_blob_indexer_gridinit_file_prefix }}\
        {{ openio_blob_indexer_servicename }}.conf"
  register: _blob_indexer_conf

- block:
    - name: present - Set properties
      set_fact:
        need_reload: true
  when:
    - _blob_indexer_conf is changed
    - not openio_blob_indexer_provision_only
...
